version: 2

sources:
  - name: public
    database: latihan_de
    schema: public
    tables:
      - name: nyc_taxi_trips
        description: "Raw NYC taxi trip data loaded via Airflow"
        loaded_at_field: loaded_at 
        freshness:
          warn_after: {count: 6, period: hour}
          error_after: {count: 24, period: hour}
      
      
      - name: olist_orders_table
        description: "Raw Olist orders data loaded via Airflow"